services:

  db:
    container_name: postgresql-go-marketplace-db
    image: postgres:18-alpine
    restart: always
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: